export type InitialProduct = {
    /**
     * Initial Order SKU for renewable subscription (Mandatory)
     */
    partNumber: string
    /**
     * Fresh value generated by the service caller. Formerly known as subscription Id (Optional)
     */
    partnerSubscriptionId?: string
    /**
     * Number of seats (Mandatory)
     */
    quantity: number
}